spring.application.name=demo

spring.security.user.name=revertpay
spring.security.user.password=12345
spring.datasource.url=jdbc:postgresql://ep-proud-scene-ayfamkar-pooler.c-5.us-east-2.aws.neon.tech/neondb?sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_DZn46VzGsUEr

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
jwt.secret=HelloMahiruuuuThisIsMyTemporaryRevertPaySecretKey1234567890
logging.level.org.springframework.security=TRACE
